window.questionBank = [
  {
    q: "Windows Forms'ta bir kontrolün ekranda görünüp görünmeyeceğini belirleyen özellik hangisidir?",
    t: "mcq",
    o: ["Visible", "Text", "Name", "Items", "Interval"],
    a: 0,
    difficulty: "easy",
    week: 1,
    topic: "Kontrol Özellikleri",
    importance: 5,
    explanation: "Visible, bir kontrolün görünür olup olmadığını belirler. true görünür, false gizli anlamına gelir."
  },
  {
    q: "Windows Forms'ta bir kontrolü kod içinde tanımak için kullanılan kimlik/ad özelliği hangisidir?",
    t: "mcq",
    o: ["Text", "Name", "BackColor", "Font", "Enabled"],
    a: 1,
    difficulty: "easy",
    week: 1,
    topic: "Name Özelliği",
    importance: 5,
    explanation: "Name, kontrolün kod tarafındaki adıdır. Örneğin txtAd, btnKaydet gibi isimler kodda bu kontrolü çağırmak için kullanılır."
  },
  {
    q: "TextBox içindeki yazı değiştiğinde çalışan olay genellikle hangisidir?",
    t: "mcq",
    o: ["Click", "Load", "TextChanged", "Tick", "Shown"],
    a: 2,
    difficulty: "medium",
    week: 3,
    topic: "TextChanged Olayı",
    importance: 4,
    explanation: "TextChanged, TextBox içindeki metin değiştiğinde tetiklenir. Anlık arama veya karakter sayma işlemlerinde kullanılabilir."
  },
  {
    q: "Bir form ilk açılırken çalışan olay hangisidir?",
    t: "mcq",
    o: ["Click", "Tick", "KeyDown", "Load", "Clear"],
    a: 3,
    difficulty: "easy",
    week: 1,
    topic: "Form Load",
    importance: 5,
    explanation: "Form Load olayı, form ekrana yüklenirken çalışır. Başlangıç değerleri genellikle burada atanır."
  },
  {
    q: "Bir kontrolün kullanıcı tarafından tıklanabilir/aktif olup olmadığını belirleyen özellik hangisidir?",
    t: "mcq",
    o: ["Text", "Name", "Items", "Visible", "Enabled"],
    a: 4,
    difficulty: "medium",
    week: 1,
    topic: "Enabled Özelliği",
    importance: 4,
    explanation: "Enabled false yapılırsa kontrol pasif olur ve kullanıcı onunla işlem yapamaz. Visible gizler, Enabled pasifleştirir."
  },
  {
    q: "Birden fazla seçeneğin aynı anda işaretlenebilmesi için hangi kontrol daha uygundur?",
    t: "mcq",
    o: ["CheckBox", "RadioButton", "Label", "TextBox", "Timer"],
    a: 0,
    difficulty: "easy",
    week: 3,
    topic: "CheckBox",
    importance: 5,
    explanation: "CheckBox, birden fazla seçeneğin aynı anda seçilebildiği durumlar için uygundur. Örneğin hobiler seçimi."
  },
  {
    q: "Açılır liste şeklinde seçim yaptırmak için hangi kontrol kullanılır?",
    t: "mcq",
    o: ["Label", "ComboBox", "PictureBox", "Timer", "Panel"],
    a: 1,
    difficulty: "easy",
    week: 3,
    topic: "ComboBox",
    importance: 5,
    explanation: "ComboBox, kullanıcıya açılır liste sunar. İl, bölüm, kategori gibi seçenekler için kullanılır."
  },
  {
    q: "Form üzerinde resim göstermek için hangi kontrol kullanılır?",
    t: "mcq",
    o: ["TextBox", "Label", "PictureBox", "Button", "ListBox"],
    a: 2,
    difficulty: "easy",
    week: 3,
    topic: "PictureBox",
    importance: 4,
    explanation: "PictureBox, form üzerinde resim göstermeye yarayan kontroldür. Logo veya fotoğraf göstermek için kullanılabilir."
  },
  {
    q: "Kullanıcıya dosya seçtirmek için kullanılan dialog hangisidir?",
    t: "mcq",
    o: ["SaveFileDialog", "ColorDialog", "FontDialog", "OpenFileDialog", "PrintDialog"],
    a: 3,
    difficulty: "medium",
    week: 3,
    topic: "OpenFileDialog",
    importance: 4,
    explanation: "OpenFileDialog, kullanıcının bilgisayardan dosya seçmesini sağlar. SaveFileDialog ise kaydetme yeri seçtirir."
  },
  {
    q: "Renk seçtirmek için kullanılan hazır dialog hangisidir?",
    t: "mcq",
    o: ["OpenFileDialog", "SaveFileDialog", "FontDialog", "PrintDialog", "ColorDialog"],
    a: 4,
    difficulty: "medium",
    week: 3,
    topic: "ColorDialog",
    importance: 3,
    explanation: "ColorDialog, kullanıcıya renk seçme penceresi açar. Seçilen renk form veya kontrol renginde kullanılabilir."
  },
  {
    q: "TextBox'tan alınan ondalıklı sayı için en uygun dönüştürme örneği hangisidir?",
    t: "mcq",
    o: ["Convert.ToDouble(txtSayi.Text)", "txtSayi.Clear()", "txtSayi.Visible", "txtSayi.Items.Add()", "txtSayi.Tick"],
    a: 0,
    difficulty: "medium",
    week: 3,
    topic: "Veri Dönüştürme",
    importance: 5,
    explanation: "TextBox.Text metin olarak gelir. Ondalıklı sayı işlemi yapılacaksa Convert.ToDouble ile double tipine çevrilir."
  },
  {
    q: "C#'ta ekrana sonuç yazdırmadan önce sayısal değeri metne çevirmek için genellikle hangi metot kullanılır?",
    t: "mcq",
    o: ["ToInt32()", "ToString()", "Clear()", "Add()", "ShowDialog()"],
    a: 1,
    difficulty: "easy",
    week: 3,
    topic: "ToString",
    importance: 5,
    explanation: "ToString(), bir değeri metne çevirir. Label.Text gibi metin bekleyen alanlarda sayıları göstermek için kullanılır."
  },
  {
    q: "Bir sayının karekökünü almak için hangi Math metodu kullanılır?",
    t: "mcq",
    o: ["Math.Pow()", "Math.Abs()", "Math.Sqrt()", "Math.Round()", "Math.Min()"],
    a: 2,
    difficulty: "easy",
    week: 2,
    topic: "Math Fonksiyonları",
    importance: 4,
    explanation: "Math.Sqrt(), karekök alır. Örneğin Math.Sqrt(9) sonucu 3 olur."
  },
  {
    q: "Bir sayının negatif olsa bile pozitif uzaklığını bulmak için hangi metot kullanılır?",
    t: "mcq",
    o: ["Math.Sqrt()", "Math.Pow()", "Math.Round()", "Math.Abs()", "Math.Max()"],
    a: 3,
    difficulty: "medium",
    week: 2,
    topic: "Math Abs",
    importance: 4,
    explanation: "Math.Abs(), mutlak değer alır. Örneğin Math.Abs(-5) sonucu 5 olur."
  },
  {
    q: "Dizideki eleman sayısını bulmak için C#'ta genellikle hangi özellik kullanılır?",
    t: "mcq",
    o: ["Text", "Visible", "Name", "Enabled", "Length"],
    a: 4,
    difficulty: "medium",
    week: 11,
    topic: "Diziler",
    importance: 5,
    explanation: "Length, dizinin kaç eleman içerdiğini verir. Ortalama hesaplarken toplamı Length değerine böleriz."
  },
  {
    q: "Bir sayının çift olup olmadığını kontrol etmek için en uygun ifade hangisidir?",
    t: "mcq",
    o: ["sayi % 2 == 0", "sayi + 2 == 0", "sayi / 2 == 0", "sayi * 2 == 0", "sayi == true"],
    a: 0,
    difficulty: "easy",
    week: 11,
    topic: "Tek Çift Kontrolü",
    importance: 5,
    explanation: "% kalan operatörüdür. Bir sayı 2'ye bölününce kalan 0 ise sayı çifttir."
  },
  {
    q: "Geriye tam sayı döndüren bir metot hangi dönüş tipiyle tanımlanır?",
    t: "mcq",
    o: ["void", "int", "string", "bool", "object"],
    a: 1,
    difficulty: "medium",
    week: 8,
    topic: "Metotlar",
    importance: 5,
    explanation: "Metot geriye tam sayı döndürecekse dönüş tipi int olmalıdır. void ise değer döndürmeyen metotlar için kullanılır."
  },
  {
    q: "try-catch yapısında beklenmeyen tüm hataları genel olarak yakalamak için hangi sınıf kullanılır?",
    t: "mcq",
    o: ["FormatException", "DivideByZeroException", "Exception", "Timer", "DialogResult"],
    a: 2,
    difficulty: "medium",
    week: 12,
    topic: "Hata Yakalama",
    importance: 5,
    explanation: "Exception genel hata sınıfıdır. Özel hata türleri yakalanmadığında genel hatalar için kullanılabilir."
  },
  {
    q: "Timer kontrolünde belirli süre doldukça çalışan olay hangisidir?",
    t: "mcq",
    o: ["Click", "Load", "TextChanged", "Tick", "Closed"],
    a: 3,
    difficulty: "medium",
    week: 3,
    topic: "Timer",
    importance: 4,
    explanation: "Timer aktifken Interval süresi doldukça Tick olayı çalışır. Sayaç ve süre işlemlerinde kullanılır."
  },
  {
    q: "Kullanıcının MessageBox üzerindeki Evet/Hayır seçimini kontrol etmek için kullanılan dönüş tipi genellikle hangisidir?",
    t: "mcq",
    o: ["int", "string", "bool only", "double", "DialogResult"],
    a: 4,
    difficulty: "hard",
    week: 3,
    topic: "DialogResult",
    importance: 3,
    explanation: "DialogResult, MessageBox gibi pencerelerden dönen sonucu temsil eder. Kullanıcı Yes, No, OK gibi seçimler yapabilir."
  },
  {
    q: "Flutter'da kullanıcı arayüzünü tarif eden ve ekrana döndüren temel metot hangisidir?",
    t: "mcq",
    o: ["build()", "main()", "runApp()", "dispose()", "pub get"],
    a: 0,
    difficulty: "easy",
    week: 3,
    topic: "Flutter build",
    importance: 5,
    explanation: "build(), widget'ın ekranda ne göstereceğini tarif eder. Flutter arayüzü build metodunun döndürdüğü widget ağacına göre oluşturur."
  },
  {
    q: "Flutter'da uygulamanın en üst widget'ını çalıştırmak için main içinde hangi fonksiyon çağrılır?",
    t: "mcq",
    o: ["setState()", "runApp()", "build()", "Navigator.pop()", "dispose()"],
    a: 1,
    difficulty: "easy",
    week: 3,
    topic: "runApp",
    importance: 5,
    explanation: "runApp(), Flutter uygulamasını başlatır. Genellikle main() içinde ana widget ile birlikte kullanılır."
  },
  {
    q: "Flutter'da değişmeyen arayüzler için kullanılan widget sınıfı hangisidir?",
    t: "mcq",
    o: ["StatefulWidget", "MaterialApp", "StatelessWidget", "Scaffold", "Navigator"],
    a: 2,
    difficulty: "easy",
    week: 3,
    topic: "StatelessWidget",
    importance: 5,
    explanation: "StatelessWidget değişebilir state tutmaz. Ekrandaki bilgi çalışma sırasında değişmeyecekse kullanılır."
  },
  {
    q: "Flutter'da sayaç gibi ekrandaki değeri değişen yapılarda hangi widget sınıfı kullanılır?",
    t: "mcq",
    o: ["StatelessWidget", "Scaffold", "Text", "StatefulWidget", "Icon"],
    a: 3,
    difficulty: "easy",
    week: 3,
    topic: "StatefulWidget",
    importance: 5,
    explanation: "StatefulWidget, değişebilir state yani durum bilgisi olan ekranlarda kullanılır. Sayaç, form ve liste ekleme buna örnektir."
  },
  {
    q: "Flutter'da StatefulWidget içinde ekranı yenilemek için hangi metot kullanılır?",
    t: "mcq",
    o: ["print()", "main()", "runApp()", "buildOnly()", "setState()"],
    a: 4,
    difficulty: "easy",
    week: 3,
    topic: "setState",
    importance: 5,
    explanation: "setState(), veri değiştiğinde Flutter'a ekranı yeniden çizmesini söyler. State değişti ama setState yoksa ekranda değişim görünmeyebilir."
  },
  {
    q: "Flutter'da bir sayfanın üst başlık çubuğunu oluşturmak için hangi widget kullanılır?",
    t: "mcq",
    o: ["AppBar", "Body", "Column", "TextField", "ListTile"],
    a: 0,
    difficulty: "easy",
    week: 3,
    topic: "AppBar",
    importance: 5,
    explanation: "AppBar, sayfanın üst kısmındaki başlık çubuğudur. Başlık, menü ve ikonlar burada gösterilebilir."
  },
  {
    q: "Flutter'da sayfanın temel Material iskeletini kuran widget hangisidir?",
    t: "mcq",
    o: ["Text", "Scaffold", "Padding", "Icon", "Image"],
    a: 1,
    difficulty: "easy",
    week: 3,
    topic: "Scaffold",
    importance: 5,
    explanation: "Scaffold, sayfanın iskeletidir. AppBar, body, drawer ve floatingActionButton gibi alanları barındırabilir."
  },
  {
    q: "Flutter'da widget'ları alt alta yerleştirmek için hangi widget kullanılır?",
    t: "mcq",
    o: ["Row", "Stack", "Column", "MaterialApp", "Navigator"],
    a: 2,
    difficulty: "easy",
    week: 3,
    topic: "Column",
    importance: 5,
    explanation: "Column, children listesindeki widget'ları dikey biçimde alt alta dizer."
  },
  {
    q: "Flutter'da widget'ları yan yana yerleştirmek için hangi widget kullanılır?",
    t: "mcq",
    o: ["Column", "Stack", "Container", "Row", "Scaffold"],
    a: 3,
    difficulty: "easy",
    week: 3,
    topic: "Row",
    importance: 5,
    explanation: "Row, widget'ları yatay yönde yan yana dizer. Column ise alt alta dizer."
  },
  {
    q: "Flutter'da widget'ların boş alanı orantılı paylaşması için hangi widget sık kullanılır?",
    t: "mcq",
    o: ["Text", "Icon", "Image", "SnackBar", "Expanded"],
    a: 4,
    difficulty: "medium",
    week: 4,
    topic: "Expanded",
    importance: 4,
    explanation: "Expanded, Row veya Column içindeki widget'ın kullanılabilir boş alanı doldurmasını sağlar. Responsive yerleşimlerde sık kullanılır."
  },
  {
    q: "Flutter'da kullanıcıdan metin girişi almak için hangi widget kullanılır?",
    t: "mcq",
    o: ["TextField", "Text", "Icon", "AppBar", "Image"],
    a: 0,
    difficulty: "easy",
    week: 5,
    topic: "TextField",
    importance: 5,
    explanation: "TextField, kullanıcıdan yazı almak için kullanılır. İsim, şifre, görev veya arama metni almak için uygundur."
  },
  {
    q: "TextField içindeki yazıyı kontrol etmek ve okumak için hangi yapı kullanılır?",
    t: "mcq",
    o: ["Navigator", "TextEditingController", "AppBar", "Scaffold", "MaterialApp"],
    a: 1,
    difficulty: "medium",
    week: 5,
    topic: "TextEditingController",
    importance: 5,
    explanation: "TextEditingController, TextField içindeki yazıyı okumak, değiştirmek ve kontrol etmek için kullanılır."
  },
  {
    q: "TextEditingController gibi kaynakları temizlemek için StatefulWidget içinde genellikle hangi metot kullanılır?",
    t: "mcq",
    o: ["build()", "runApp()", "dispose()", "main()", "push()"],
    a: 2,
    difficulty: "hard",
    week: 5,
    topic: "dispose",
    importance: 4,
    explanation: "dispose(), widget artık kullanılmayacakken kaynakları temizlemek için çalışır. Controller gibi nesneler burada temizlenebilir."
  },
  {
    q: "Flutter'da çok sayıda veriyi performanslı listelemek için hangi yapı yaygın kullanılır?",
    t: "mcq",
    o: ["Text.only", "Column.only", "Container.all", "ListView.builder", "MaterialApp.body"],
    a: 3,
    difficulty: "medium",
    week: 5,
    topic: "ListView.builder",
    importance: 5,
    explanation: "ListView.builder, liste elemanlarını ihtiyaç oldukça üretir. Çok sayıda veri gösterirken performans açısından daha uygundur."
  },
  {
    q: "Flutter'da sayfalar arasında ileri geçiş yapmak için genellikle hangi Navigator metodu kullanılır?",
    t: "mcq",
    o: ["pop()", "dispose()", "setState()", "build()", "push()"],
    a: 4,
    difficulty: "medium",
    week: 5,
    topic: "Navigator push",
    importance: 5,
    explanation: "Navigator.push(), yeni bir sayfayı ekran yığınına ekler ve kullanıcıyı o sayfaya götürür. Geri dönüş için pop() kullanılır."
  },
  {
    q: "Flutter'da önceki sayfaya geri dönmek için hangi Navigator metodu kullanılır?",
    t: "mcq",
    o: ["Navigator.pop(context)", "Navigator.run(context)", "Navigator.build(context)", "Navigator.state(context)", "Navigator.reload(context)"],
    a: 0,
    difficulty: "easy",
    week: 5,
    topic: "Navigator pop",
    importance: 5,
    explanation: "Navigator.pop(context), mevcut sayfayı kapatır ve önceki sayfaya döner."
  },
  {
    q: "Flutter projesinde paket ve asset tanımlamaları hangi dosyada yapılır?",
    t: "mcq",
    o: ["main.dart", "pubspec.yaml", "index.html", "database.sql", "style.css"],
    a: 1,
    difficulty: "easy",
    week: 6,
    topic: "pubspec.yaml",
    importance: 5,
    explanation: "pubspec.yaml, Flutter projesinin yapılandırma dosyasıdır. Paketler, assetler, fontlar ve sürüm bilgileri burada tanımlanır."
  },
  {
    q: "pubspec.yaml dosyasına yeni paket eklendikten sonra bağımlılıkları indirmek için hangi komut kullanılır?",
    t: "mcq",
    o: ["flutter clean only", "dart print", "flutter pub get", "flutter delete", "flutter stop"],
    a: 2,
    difficulty: "medium",
    week: 6,
    topic: "flutter pub get",
    importance: 5,
    explanation: "flutter pub get, pubspec.yaml içindeki paketleri indirir ve projeye hazırlar."
  },
  {
    q: "Flutter'da kullanıcıya kısa süreli alt uyarı mesajı göstermek için hangi widget kullanılır?",
    t: "mcq",
    o: ["AppBar", "Column", "Container", "SnackBar", "MaterialApp"],
    a: 3,
    difficulty: "medium",
    week: 7,
    topic: "SnackBar",
    importance: 4,
    explanation: "SnackBar, kullanıcıya kısa bilgi mesajı göstermek için kullanılır. Örneğin 'Görev eklendi' mesajı."
  },
  {
    q: "Flutter'da ekran ölçüsü gibi cihaz bilgilerini almak için hangi yapı kullanılır?",
    t: "mcq",
    o: ["Text", "Icon", "Button", "Navigator", "MediaQuery"],
    a: 4,
    difficulty: "medium",
    week: 8,
    topic: "MediaQuery",
    importance: 4,
    explanation: "MediaQuery, ekran genişliği, yüksekliği ve cihaz bilgilerini almak için kullanılır. Responsive tasarımda önemlidir."
  },
  {
    q: "PHP kodları genellikle hangi yapı içinde yazılır?",
    t: "mcq",
    o: ["PHP açılış ve kapanış etiketi", "HTML kapanış etiketi", "CSS bloğu", "SQL tablo etiketi", "Script type etiketi"],
    a: 0,
    difficulty: "easy",
    week: 3,
    topic: "PHP Temel Sözdizimi",
    importance: 5,
    explanation: "PHP kodları PHP açılış ve kapanış etiketi arasında yazılır. Sunucu bu aradaki kodları PHP olarak yorumlar."
  },
  {
    q: "PHP'de değişkenler hangi sembol ile başlar?",
    t: "mcq",
    o: ["#", "$", "@", "&", "%"],
    a: 1,
    difficulty: "easy",
    week: 3,
    topic: "PHP Değişken",
    importance: 5,
    explanation: "PHP'de değişkenler $ işareti ile başlar. Örneğin $ad, $yas, $sonuc gibi."
  },
  {
    q: "PHP'de ekrana yazı yazdırmak için en sık kullanılan ifade hangisidir?",
    t: "mcq",
    o: ["input", "select", "echo", "where", "mkdir"],
    a: 2,
    difficulty: "easy",
    week: 3,
    topic: "echo",
    importance: 5,
    explanation: "echo, PHP'de ekrana metin veya değişken değeri yazdırmak için kullanılır."
  },
  {
    q: "PHP'de aynı değişkenin farklı sabit değerlerine göre işlem yapmak için en uygun yapı hangisidir?",
    t: "mcq",
    o: ["for", "while", "foreach", "switch-case", "include"],
    a: 3,
    difficulty: "easy",
    week: 3,
    topic: "switch-case",
    importance: 5,
    explanation: "switch-case, bir değişkenin farklı değerlerine göre işlem yapmayı sağlar. Menü seçimlerinde sık kullanılır."
  },
  {
    q: "PHP'de bir dizinin elemanlarını tek tek gezmek için en uygun döngü hangisidir?",
    t: "mcq",
    o: ["if", "else", "switch", "echo", "foreach"],
    a: 4,
    difficulty: "easy",
    week: 4,
    topic: "foreach",
    importance: 5,
    explanation: "foreach, dizi elemanlarını sırayla dolaşmak için kullanılır. Her eleman üzerinde işlem yapılmasını kolaylaştırır."
  },
  {
    q: "PHP'de bir metindeki belirli karakter aralığını almak için hangi fonksiyon kullanılır?",
    t: "mcq",
    o: ["substr()", "strlen()", "trim()", "strtolower()", "explode()"],
    a: 0,
    difficulty: "easy",
    week: 5,
    topic: "substr",
    importance: 5,
    explanation: "substr(), string içinden belirli başlangıç ve uzunluğa göre parça alır. Alt metin çıkarmak için kullanılır."
  },
  {
    q: "PHP'de bir metindeki kelimeyi başka bir kelimeyle değiştirmek için hangi fonksiyon kullanılır?",
    t: "mcq",
    o: ["strlen()", "str_replace()", "substr()", "trim()", "mb_strlen()"],
    a: 1,
    difficulty: "easy",
    week: 5,
    topic: "str_replace",
    importance: 5,
    explanation: "str_replace(), bir metindeki aranan ifadeyi yeni ifadeyle değiştirir."
  },
  {
    q: "PHP'de metni diziye bölmek için genellikle hangi fonksiyon kullanılır?",
    t: "mcq",
    o: ["implode()", "trim()", "explode()", "strlen()", "ucfirst()"],
    a: 2,
    difficulty: "medium",
    week: 5,
    topic: "explode",
    importance: 4,
    explanation: "explode(), belirli ayırıcıya göre metni parçalara böler ve dizi döndürür. Örneğin virgülle ayrılmış sayıları ayırmak için kullanılır."
  },
  {
    q: "HTML formunda PHP tarafında okunacak alan adını belirleyen özellik hangisidir?",
    t: "mcq",
    o: ["id", "class", "style", "name", "src"],
    a: 3,
    difficulty: "easy",
    week: 6,
    topic: "Form name",
    importance: 5,
    explanation: "name özelliği, form verisinin PHP tarafında hangi anahtarla geleceğini belirler. Örneğin name='ad' için $_POST['ad'] kullanılır."
  },
  {
    q: "HTML formunda verinin gönderileceği PHP dosyasını belirleyen özellik hangisidir?",
    t: "mcq",
    o: ["name", "method", "type", "value", "action"],
    a: 4,
    difficulty: "easy",
    week: 6,
    topic: "Form action",
    importance: 5,
    explanation: "action, form gönderildiğinde isteğin hangi PHP dosyasına gideceğini belirtir."
  },
  {
    q: "Şifre gibi URL'de görünmemesi gereken form verileri için hangi yöntem daha uygundur?",
    t: "mcq",
    o: ["POST", "GET", "REQUEST", "LINK", "TRACE"],
    a: 0,
    difficulty: "easy",
    week: 6,
    topic: "POST",
    importance: 5,
    explanation: "POST, veriyi URL'de göstermez; HTTP isteğinin gövdesinde taşır. Bu yüzden formlar ve hassas veriler için GET'e göre daha uygundur."
  },
  {
    q: "PHP'de dosya yükleme işleminde geçici dosya yolunu veren $_FILES alanı hangisidir?",
    t: "mcq",
    o: ["name", "tmp_name", "type", "size", "error"],
    a: 1,
    difficulty: "medium",
    week: 7,
    topic: "tmp_name",
    importance: 5,
    explanation: "tmp_name, yüklenen dosyanın sunucuda geçici olarak tutulduğu yolu verir. Dosya kalıcı klasöre buradan taşınır."
  },
  {
    q: "PHP dosya yükleme işleminde dosya boyutu hangi $_FILES alanından okunur?",
    t: "mcq",
    o: ["name", "type", "size", "tmp_name", "error"],
    a: 2,
    difficulty: "easy",
    week: 7,
    topic: "Dosya Boyutu",
    importance: 4,
    explanation: "size, yüklenen dosyanın boyut bilgisini verir. Dosya boyutu kontrolü güvenlik için önemlidir."
  },
  {
    q: "Oturum kullanmadan önce PHP dosyasının başında hangi fonksiyon çağrılmalıdır?",
    t: "mcq",
    o: ["session_destroy()", "setcookie()", "mysqli_connect()", "session_start()", "password_hash()"],
    a: 3,
    difficulty: "easy",
    week: 8,
    topic: "session_start",
    importance: 5,
    explanation: "session_start(), oturumu başlatır. $_SESSION değişkeniyle sağlıklı çalışmak için sayfanın başında çağrılır."
  },
  {
    q: "PHP'de tarayıcıda saklanan küçük verilere erişmek için hangi süper global kullanılır?",
    t: "mcq",
    o: ["$_GET", "$_POST", "$_SESSION", "$_FILES", "$_COOKIE"],
    a: 4,
    difficulty: "medium",
    week: 8,
    topic: "Cookie",
    importance: 4,
    explanation: "$_COOKIE, tarayıcıda saklanan çerez verilerine erişir. Session genelde sunucuda tutulur, cookie istemci tarafındadır."
  },
  {
    q: "PHP'de oturumu tamamen bitirmek için hangi fonksiyon kullanılır?",
    t: "mcq",
    o: ["session_destroy()", "session_start()", "session_id()", "setcookie()", "header()"],
    a: 0,
    difficulty: "easy",
    week: 8,
    topic: "session_destroy",
    importance: 5,
    explanation: "session_destroy(), aktif oturumu sonlandırır. Çıkış/logout işleminde kullanılır."
  },
  {
    q: "PHP'de MySQL bağlantısı için kullanılan geliştirilmiş eklenti hangisidir?",
    t: "mcq",
    o: ["PDO only", "mysqli", "session", "cookie", "strlen"],
    a: 1,
    difficulty: "easy",
    week: 9,
    topic: "mysqli",
    importance: 5,
    explanation: "mysqli, PHP ile MySQL veritabanı arasında bağlantı ve sorgu işlemleri yapmak için kullanılan eklentidir."
  },
  {
    q: "Prepared statement içinde sorguyu çalıştıran metot hangisidir?",
    t: "mcq",
    o: ["prepare()", "bind_param()", "execute()", "fetch_only()", "connect()"],
    a: 2,
    difficulty: "medium",
    week: 11,
    topic: "execute",
    importance: 5,
    explanation: "execute(), daha önce prepare ile hazırlanmış sorguyu çalıştırır. prepare hazırlar, bind_param veri bağlar, execute çalıştırır."
  },
  {
    q: "SQL'de mevcut bir kaydı değiştirmek için hangi komut kullanılır?",
    t: "mcq",
    o: ["INSERT", "SELECT", "DELETE", "UPDATE", "CREATE"],
    a: 3,
    difficulty: "easy",
    week: 13,
    topic: "UPDATE",
    importance: 5,
    explanation: "UPDATE, var olan kaydın değerlerini değiştirmek için kullanılır. Genellikle WHERE ile hedef kayıt seçilir."
  },
  {
    q: "file_put_contents() ile dosya sonuna ekleme yapmak için hangi sabit kullanılır?",
    t: "mcq",
    o: ["FILE_START", "FILE_WRITE", "FILE_READ", "FILE_END", "FILE_APPEND"],
    a: 4,
    difficulty: "medium",
    week: 14,
    topic: "FILE_APPEND",
    importance: 5,
    explanation: "FILE_APPEND, mevcut dosya içeriğini silmeden dosyanın sonuna ekleme yapılmasını sağlar."
  },
  {
    q: "İlişkisel veritabanında veriler temel olarak hangi yapıda saklanır?",
    t: "mcq",
    o: ["Tablo", "Resim", "Video", "CSS dosyası", "Tarayıcı geçmişi"],
    a: 0,
    difficulty: "easy",
    week: 1,
    topic: "İlişkisel Veritabanı",
    importance: 5,
    explanation: "İlişkisel veritabanında veriler satır ve sütunlardan oluşan tablolar içinde saklanır."
  },
  {
    q: "Bir tabloda yatay kayıt satırına genellikle ne denir?",
    t: "mcq",
    o: ["Sütun", "Satır/Kayıt", "Veritabanı", "İndeks", "Şema"],
    a: 1,
    difficulty: "easy",
    week: 1,
    topic: "Satır Kayıt",
    importance: 5,
    explanation: "Satır veya kayıt, tablodaki tek bir veri örneğini temsil eder. Örneğin bir öğrenci bilgisi bir satır olabilir."
  },
  {
    q: "Bir tabloda aynı tür bilgileri tutan dikey alana ne denir?",
    t: "mcq",
    o: ["Kayıt", "Satır", "Sütun/Alan", "Backup", "Transaction"],
    a: 2,
    difficulty: "easy",
    week: 1,
    topic: "Sütun Alan",
    importance: 5,
    explanation: "Sütun, tablodaki aynı tür bilgileri tutar. Örneğin ad, soyad, yaş birer sütundur."
  },
  {
    q: "SQL Server'da otomatik artan sayı üretmek için kullanılan özellik hangisidir?",
    t: "mcq",
    o: ["VARCHAR", "NOT NULL", "FOREIGN KEY", "IDENTITY", "ORDER BY"],
    a: 3,
    difficulty: "medium",
    week: 2,
    topic: "IDENTITY",
    importance: 5,
    explanation: "IDENTITY, SQL Server'da genellikle id alanının otomatik artmasını sağlar. MySQL'deki AUTO_INCREMENT mantığına benzer."
  },
  {
    q: "Bir alana boş değer girilmesini engelleyen kısıt hangisidir?",
    t: "mcq",
    o: ["PRIMARY KEY only", "ORDER BY", "GROUP BY", "SELECT", "NOT NULL"],
    a: 4,
    difficulty: "easy",
    week: 2,
    topic: "NOT NULL",
    importance: 5,
    explanation: "NOT NULL, ilgili sütunun boş bırakılmasını engeller. Veri bütünlüğünü korur."
  },
  {
    q: "Bir sütundaki değerlerin tekrar etmesini engelleyen kısıt hangisidir?",
    t: "mcq",
    o: ["UNIQUE", "WHERE", "FROM", "JOIN", "BACKUP"],
    a: 0,
    difficulty: "medium",
    week: 2,
    topic: "UNIQUE",
    importance: 4,
    explanation: "UNIQUE kısıtı, bir sütundaki değerlerin tekrarlanmasını engeller. Örneğin e-posta alanında kullanılabilir."
  },
  {
    q: "Bir sütuna değer girilmediğinde otomatik atanacak değeri belirleyen kısıt hangisidir?",
    t: "mcq",
    o: ["CHECK", "DEFAULT", "ORDER BY", "HAVING", "JOIN"],
    a: 1,
    difficulty: "medium",
    week: 2,
    topic: "DEFAULT",
    importance: 4,
    explanation: "DEFAULT, kullanıcı değer girmezse kullanılacak varsayılan değeri belirler."
  },
  {
    q: "Bir sütundaki değerin belirli şartı sağlamasını zorunlu kılan kısıt hangisidir?",
    t: "mcq",
    o: ["SELECT", "INSERT", "CHECK", "BACKUP", "VIEW"],
    a: 2,
    difficulty: "medium",
    week: 2,
    topic: "CHECK",
    importance: 4,
    explanation: "CHECK kısıtı, değerlerin belirli kurala uymasını sağlar. Örneğin yaş >= 18 şartı verilebilir."
  },
  {
    q: "SQL'de tablo yapısını değiştirmek için hangi komut kullanılır?",
    t: "mcq",
    o: ["SELECT", "INSERT", "DELETE", "ALTER TABLE", "ORDER BY"],
    a: 3,
    difficulty: "medium",
    week: 3,
    topic: "ALTER TABLE",
    importance: 4,
    explanation: "ALTER TABLE, mevcut tablonun yapısını değiştirmek için kullanılır. Yeni sütun ekleme veya sütun değiştirme işlemleri yapılabilir."
  },
  {
    q: "SQL'de tabloyu tamamen silmek için hangi komut kullanılır?",
    t: "mcq",
    o: ["DELETE ROW", "SELECT", "UPDATE", "WHERE", "DROP TABLE"],
    a: 4,
    difficulty: "medium",
    week: 3,
    topic: "DROP TABLE",
    importance: 5,
    explanation: "DROP TABLE, tabloyu yapısıyla birlikte siler. DELETE ise tablodaki kayıtları siler, tablo yapısını silmez."
  },
  {
    q: "SELECT * FROM Ogrenciler ifadesindeki * ne anlama gelir?",
    t: "mcq",
    o: ["Tüm sütunları getir", "Sadece ilk satırı getir", "Tabloyu sil", "Veritabanı oluştur", "Kayıt ekle"],
    a: 0,
    difficulty: "easy",
    week: 4,
    topic: "SELECT",
    importance: 5,
    explanation: "* işareti tüm sütunları seçmek için kullanılır. SELECT * FROM Ogrenciler tüm alanları getirir."
  },
  {
    q: "SQL'de sadece farklı/tekrarsız değerleri getirmek için hangi ifade kullanılır?",
    t: "mcq",
    o: ["ORDER BY", "DISTINCT", "JOIN", "DELETE", "DROP"],
    a: 1,
    difficulty: "medium",
    week: 4,
    topic: "DISTINCT",
    importance: 4,
    explanation: "DISTINCT, tekrar eden değerleri tekilleştirir. Örneğin aynı şehir adlarını bir kez göstermek için kullanılır."
  },
  {
    q: "SQL'de belirli bir metin desenine göre arama yapmak için hangi operatör kullanılır?",
    t: "mcq",
    o: ["INTO", "DROP", "LIKE", "CREATE", "DEFAULT"],
    a: 2,
    difficulty: "medium",
    week: 4,
    topic: "LIKE",
    importance: 5,
    explanation: "LIKE, metin desenine göre arama yapar. Örneğin Ad LIKE 'A%' A ile başlayan adları getirir."
  },
  {
    q: "SQL'de birden fazla olası değerden herhangi birine eşit olan kayıtları seçmek için hangi operatör kullanılır?",
    t: "mcq",
    o: ["LIKE", "JOIN", "ORDER", "IN", "DROP"],
    a: 3,
    difficulty: "medium",
    week: 4,
    topic: "IN",
    importance: 4,
    explanation: "IN, bir değerin verilen liste içindeki değerlerden biri olup olmadığını kontrol eder."
  },
  {
    q: "SQL'de iki değer aralığındaki kayıtları seçmek için hangi operatör kullanılır?",
    t: "mcq",
    o: ["LIKE", "IN", "JOIN", "CREATE", "BETWEEN"],
    a: 4,
    difficulty: "medium",
    week: 4,
    topic: "BETWEEN",
    importance: 4,
    explanation: "BETWEEN, iki değer arasındaki kayıtları seçer. Örneğin yas BETWEEN 18 AND 25."
  },
  {
    q: "INNER JOIN ne yapar?",
    t: "mcq",
    o: ["İki tabloda eşleşen kayıtları getirir", "Sol tablonun tüm kayıtlarını koşulsuz getirir", "Tabloyu siler", "Yedek alır", "Sütun ekler"],
    a: 0,
    difficulty: "medium",
    week: 5,
    topic: "INNER JOIN",
    importance: 5,
    explanation: "INNER JOIN, iki tabloda eşleşen kayıtları getirir. Eşleşmeyen kayıtlar sonuçta yer almaz."
  },
  {
    q: "COUNT() fonksiyonu ne işe yarar?",
    t: "mcq",
    o: ["Ortalama alır", "Kayıt sayısını bulur", "En büyük değeri bulur", "Tabloyu siler", "Metin birleştirir"],
    a: 1,
    difficulty: "easy",
    week: 5,
    topic: "COUNT",
    importance: 5,
    explanation: "COUNT(), kayıt sayısını verir. Örneğin SELECT COUNT(*) FROM Ogrenciler toplam öğrenci sayısını döndürür."
  },
  {
    q: "AVG() fonksiyonu ne işe yarar?",
    t: "mcq",
    o: ["Toplam alır", "En küçük değeri bulur", "Ortalama hesaplar", "Sıralama yapar", "Silme yapar"],
    a: 2,
    difficulty: "easy",
    week: 5,
    topic: "AVG",
    importance: 5,
    explanation: "AVG(), sayısal değerlerin ortalamasını hesaplar. Not ortalaması gibi işlemlerde kullanılır."
  },
  {
    q: "GROUP BY ne için kullanılır?",
    t: "mcq",
    o: ["Tablo silmek için", "Kayıt eklemek için", "Alan adı değiştirmek için", "Kayıtları gruplamak için", "Veritabanı kapatmak için"],
    a: 3,
    difficulty: "medium",
    week: 5,
    topic: "GROUP BY",
    importance: 5,
    explanation: "GROUP BY, kayıtları belirli sütuna göre gruplar. Örneğin bölümlere göre öğrenci sayısı almak için kullanılır."
  },
  {
    q: "GROUP BY sonrası gruplara koşul uygulamak için hangi ifade kullanılır?",
    t: "mcq",
    o: ["WHERE only", "ORDER ONLY", "JOIN ONLY", "DROP", "HAVING"],
    a: 4,
    difficulty: "hard",
    week: 5,
    topic: "HAVING",
    importance: 4,
    explanation: "HAVING, gruplandırılmış sonuçlar üzerinde koşul uygulamak için kullanılır. WHERE satırlara, HAVING gruplara uygulanır."
  }
];
