window.questionBank = [
  // =========================================================
  // ===================== AĞ TEMELLERİ ======================
  // =========================================================

  {
    q: "Alan adlarını IP adreslerine çeviren sistem hangisidir?",
    t: "mcq",
    o: ["ARP", "DNS", "FTP", "SMTP", "ICMP"],
    a: 1,
    difficulty: "easy",
    week: 7,
    topic: "DNS",
    importance: 5,
    explanation: "Soruda alan adı, domain veya IP adresine çevirme geçiyorsa cevap DNS olur. DNS, google.com gibi isimleri IP adresine çevirir."
  },
  {
    q: "IP adresini MAC adresine çevirmek için kullanılan protokol hangisidir?",
    t: "mcq",
    o: ["HTTP", "SMTP", "ARP", "FTP", "DNS"],
    a: 2,
    difficulty: "medium",
    week: 11,
    topic: "ARP",
    importance: 5,
    explanation: "Soruda IP'den MAC adresi bulma geçiyorsa cevap ARP olur. DNS isimden IP bulur, ARP ise IP'den MAC adresi bulur."
  },
  {
    q: "Bir hedefe ulaşılıp ulaşılamadığını ve gecikmeyi test eden komut hangisidir?",
    t: "mcq",
    o: ["ping", "ipconfig", "netstat", "nslookup", "route print"],
    a: 0,
    difficulty: "easy",
    week: 12,
    topic: "ping",
    importance: 5,
    explanation: "Soruda erişim testi, gecikme, paket kaybı veya hedefe ulaşılıyor mu ifadesi varsa cevap ping olur."
  },
  {
    q: "ping komutu hangi protokolü kullanır?",
    t: "mcq",
    o: ["FTP", "HTTP", "SMTP", "ICMP", "POP3"],
    a: 3,
    difficulty: "medium",
    week: 12,
    topic: "ICMP",
    importance: 5,
    explanation: "ping komutu ICMP kullanır. Sınavda ping hangi protokol ile çalışır diye sorulursa cevap ICMP'dir."
  },
  {
    q: "Paketin hedefe giderken geçtiği routerları gösteren komut hangisidir?",
    t: "mcq",
    o: ["nslookup", "tracert / traceroute", "ipconfig", "arp -a", "curl"],
    a: 1,
    difficulty: "medium",
    week: 12,
    topic: "tracert",
    importance: 5,
    explanation: "Soruda paketin geçtiği yol, hop, routerlar veya hedefe giderken izlediği yol deniyorsa cevap tracert/traceroute olur."
  },
  {
    q: "Windows'ta IP adresi, varsayılan ağ geçidi ve DNS bilgilerini gösteren komut hangisidir?",
    t: "mcq",
    o: ["netstat", "nslookup", "ipconfig", "telnet", "ping"],
    a: 2,
    difficulty: "easy",
    week: 12,
    topic: "ipconfig",
    importance: 5,
    explanation: "Soruda IP bilgisi, gateway veya DNS adreslerini görme geçiyorsa Windows tarafında cevap ipconfig olur."
  },
  {
    q: "DNS sorgusu yapmak için kullanılan komut hangisidir?",
    t: "mcq",
    o: ["ping", "tracert", "ipconfig", "nslookup", "netstat"],
    a: 3,
    difficulty: "medium",
    week: 12,
    topic: "nslookup",
    importance: 5,
    explanation: "Soruda DNS sorgusu veya alan adının hangi IP'ye gittiğini öğrenme geçiyorsa cevap nslookup olur."
  },
  {
    q: "Açık portları ve aktif bağlantıları görüntülemek için kullanılan komut hangisidir?",
    t: "mcq",
    o: ["netstat", "ping", "nslookup", "ipconfig", "tracert"],
    a: 0,
    difficulty: "medium",
    week: 12,
    topic: "netstat",
    importance: 5,
    explanation: "Soruda açık port, aktif bağlantı veya bağlantı listesi geçiyorsa cevap netstat olur."
  },
  {
    q: "Farklı ağlar arasında veri yönlendiren cihaz hangisidir?",
    t: "mcq",
    o: ["Switch", "Hub", "Router", "Access Point", "Repeater"],
    a: 2,
    difficulty: "easy",
    week: 2,
    topic: "Router",
    importance: 5,
    explanation: "Soruda farklı ağları bağlama, yönlendirme veya IP'ye göre paket gönderme geçiyorsa cevap Router olur."
  },
  {
    q: "Aynı yerel ağdaki cihazları birbirine bağlayan ve veriyi hedef cihaza gönderen cihaz hangisidir?",
    t: "mcq",
    o: ["Firewall", "Modem", "Hub", "Switch", "Proxy"],
    a: 3,
    difficulty: "easy",
    week: 2,
    topic: "Switch",
    importance: 5,
    explanation: "Soruda aynı ağ, MAC adresi veya hedef cihaza gönderme geçiyorsa cevap Switch olur."
  },
  {
    q: "Gelen veriyi hedef ayırmadan tüm portlara gönderen cihaz hangisidir?",
    t: "mcq",
    o: ["Hub", "Router", "Switch", "Firewall", "Access Point"],
    a: 0,
    difficulty: "easy",
    week: 2,
    topic: "Hub",
    importance: 5,
    explanation: "Soruda veriyi herkese gönderir, verimsizdir veya çakışmaya neden olur deniyorsa cevap Hub olur."
  },
  {
    q: "Ağ trafiğini güvenlik kurallarına göre izinli veya engelli olarak ayıran cihaz hangisidir?",
    t: "mcq",
    o: ["Hub", "Firewall", "Switch", "Modem", "Repeater"],
    a: 1,
    difficulty: "easy",
    week: 2,
    topic: "Firewall",
    importance: 5,
    explanation: "Soruda güvenlik, zararlı trafik, engelleme veya izin verme geçiyorsa cevap Firewall olur."
  },
  {
    q: "Kablosuz cihazların ağa bağlanmasını sağlayan cihaz hangisidir?",
    t: "mcq",
    o: ["Router only", "Hub", "Access Point", "Firewall", "Proxy"],
    a: 2,
    difficulty: "easy",
    week: 2,
    topic: "Access Point",
    importance: 5,
    explanation: "Soruda Wi-Fi dağıtma, kablosuz bağlantı veya SSID geçiyorsa cevap Access Point olur."
  },
  {
    q: "İnternet servis sağlayıcısından gelen bağlantıyı ev veya ofis ağı için kullanılabilir hale getiren cihaz hangisidir?",
    t: "mcq",
    o: ["Switch", "Hub", "Firewall", "Modem", "Load Balancer"],
    a: 3,
    difficulty: "easy",
    week: 2,
    topic: "Modem",
    importance: 4,
    explanation: "Soruda internet servis sağlayıcısı, bağlantı veya sinyal dönüştürme geçiyorsa cevap Modem olur."
  },
  {
    q: "TCP protokolünün en temel özelliği hangisidir?",
    t: "mcq",
    o: ["Güvenilir ve bağlantılı çalışması", "Bağlantısız ve en hızlı olması", "Alan adını IP'ye çevirmesi", "IP'yi MAC'e çevirmesi", "Sadece kablosuz çalışması"],
    a: 0,
    difficulty: "medium",
    week: 6,
    topic: "TCP",
    importance: 5,
    explanation: "Soruda güvenilir, bağlantılı, hata kontrolü, sıralama veya tekrar gönderim geçiyorsa TCP düşünülür."
  },
  {
    q: "UDP protokolünün en temel özelliği hangisidir?",
    t: "mcq",
    o: ["Güvenilir ve bağlantılı çalışması", "Alan adını çözmesi", "Hızlı ve bağlantısız çalışması", "Dosya transferi yapması", "MAC adresi bulması"],
    a: 2,
    difficulty: "medium",
    week: 6,
    topic: "UDP",
    importance: 5,
    explanation: "Soruda hızlı, bağlantısız, canlı yayın, oyun, VoIP veya düşük gecikme geçiyorsa UDP düşünülür."
  },
  {
    q: "TCP bağlantısı kurulurken kullanılan SYN, SYN-ACK ve ACK adımlarından oluşan süreç nedir?",
    t: "mcq",
    o: ["DNS çözümleme", "ARP sorgusu", "ICMP testi", "3-Way Handshake", "Port tarama"],
    a: 3,
    difficulty: "hard",
    week: 6,
    topic: "3-Way Handshake",
    importance: 5,
    explanation: "Soruda SYN, SYN-ACK ve ACK kelimeleri geçiyorsa cevap 3-Way Handshake olur."
  },
  {
    q: "Web sayfalarının tarayıcı üzerinden açılmasında kullanılan protokol hangisidir?",
    t: "mcq",
    o: ["HTTP / HTTPS", "FTP", "SMTP", "ARP", "ICMP"],
    a: 0,
    difficulty: "easy",
    week: 7,
    topic: "HTTP HTTPS",
    importance: 5,
    explanation: "Soruda web, tarayıcı, site açma veya güvenli web geçiyorsa HTTP/HTTPS düşünülür."
  },
  {
    q: "Dosya aktarımı için kullanılan protokol hangisidir?",
    t: "mcq",
    o: ["DNS", "FTP", "ICMP", "ARP", "POP3"],
    a: 1,
    difficulty: "easy",
    week: 7,
    topic: "FTP",
    importance: 5,
    explanation: "Soruda dosya gönderme, dosya alma veya file transfer geçiyorsa cevap FTP olur."
  },
  {
    q: "E-posta göndermek için kullanılan protokol hangisidir?",
    t: "mcq",
    o: ["IMAP", "POP3", "SMTP", "DNS", "ARP"],
    a: 2,
    difficulty: "easy",
    week: 7,
    topic: "SMTP",
    importance: 5,
    explanation: "Soruda mail gönderme geçiyorsa cevap SMTP olur. POP3 ve IMAP mail alma tarafındadır."
  },
  {
    q: "E-posta almak için kullanılan protokoller hangileridir?",
    t: "mcq",
    o: ["HTTP ve HTTPS", "FTP ve DNS", "ARP ve ICMP", "POP3 ve IMAP", "TCP ve UDP"],
    a: 3,
    difficulty: "easy",
    week: 7,
    topic: "POP3 IMAP",
    importance: 5,
    explanation: "Soruda mail alma, sunucudan e-posta çekme veya e-postayı yönetme geçiyorsa POP3/IMAP düşünülür."
  },
  {
    q: "OSI modeli kaç katmandan oluşur?",
    t: "mcq",
    o: ["7", "4", "5", "3", "8"],
    a: 0,
    difficulty: "easy",
    week: 8,
    topic: "OSI Modeli",
    importance: 5,
    explanation: "OSI modeli sorulursa katman sayısı 7'dir. TCP/IP modeli ise 4 katmandır."
  },
  {
    q: "OSI modelinde IP adresleme ve routing hangi katmandadır?",
    t: "mcq",
    o: ["Fiziksel", "Ağ", "Sunum", "Uygulama", "Oturum"],
    a: 1,
    difficulty: "medium",
    week: 8,
    topic: "Ağ Katmanı",
    importance: 5,
    explanation: "Soruda IP, router, routing veya yönlendirme geçiyorsa OSI katmanı Ağ katmanıdır."
  },
  {
    q: "OSI modelinde TCP ve UDP hangi katmanda çalışır?",
    t: "mcq",
    o: ["Veri Bağlantı", "Fiziksel", "Taşıma", "Sunum", "Oturum"],
    a: 2,
    difficulty: "medium",
    week: 8,
    topic: "Taşıma Katmanı",
    importance: 5,
    explanation: "TCP ve UDP taşıma katmanı protokolleridir. Soruda TCP/UDP katmanı sorulursa cevap Taşıma olur."
  },
  {
    q: "OSI modelinde MAC adresleme ve çerçeveleme hangi katmanla ilgilidir?",
    t: "mcq",
    o: ["Uygulama", "Sunum", "Ağ", "Veri Bağlantı", "Taşıma"],
    a: 3,
    difficulty: "medium",
    week: 8,
    topic: "Veri Bağlantı Katmanı",
    importance: 5,
    explanation: "Soruda MAC adresi, switch veya frame/çerçeve geçiyorsa Veri Bağlantı katmanı düşünülür."
  },
  {
    q: "OSI modelinde kablo, bit ve elektriksel sinyal iletimi hangi katmandadır?",
    t: "mcq",
    o: ["Fiziksel", "Taşıma", "Ağ", "Uygulama", "Oturum"],
    a: 0,
    difficulty: "easy",
    week: 8,
    topic: "Fiziksel Katman",
    importance: 5,
    explanation: "Soruda kablo, bit, sinyal veya fiziksel iletim geçiyorsa cevap Fiziksel katman olur."
  },
  {
    q: "TCP/IP modeli kaç katmandan oluşur?",
    t: "mcq",
    o: ["7", "4", "6", "8", "3"],
    a: 1,
    difficulty: "easy",
    week: 10,
    topic: "TCP/IP Modeli",
    importance: 5,
    explanation: "TCP/IP modeli 4 katmandır. OSI modeli 7 katmandır."
  },
  {
    q: "Merkezi bir switch veya router etrafında kurulan, küçük ofislerde sık kullanılan topoloji hangisidir?",
    t: "mcq",
    o: ["Bus", "Ring", "Star", "Mesh", "Tree"],
    a: 2,
    difficulty: "easy",
    week: 3,
    topic: "Star Topoloji",
    importance: 5,
    explanation: "Soruda merkezi cihaz, küçük ofis veya kolay yönetim geçiyorsa cevap Star/Yıldız topoloji olur."
  },
  {
    q: "Yedek yollar sayesinde güvenilir olan fakat maliyeti yüksek topoloji hangisidir?",
    t: "mcq",
    o: ["Bus", "Ring", "Star", "Mesh", "Point-to-point"],
    a: 3,
    difficulty: "medium",
    week: 3,
    topic: "Mesh Topoloji",
    importance: 5,
    explanation: "Soruda yedek yol, kesintisizlik, çok bağlantı ve pahalı geçiyorsa cevap Mesh topoloji olur."
  },
  {
    q: "Parazite karşı UTP kablodan daha korumalı olan kablo türü hangisidir?",
    t: "mcq",
    o: ["STP", "UTP", "HDMI", "VGA", "USB"],
    a: 0,
    difficulty: "medium",
    week: 4,
    topic: "STP Kablo",
    importance: 5,
    explanation: "Soruda korumalı, shielded, parazit veya elektromanyetik etki geçiyorsa cevap STP olur."
  },

  // =========================================================
  // ============ NESNE YÖNELİMLİ PROGRAMLAMA ================
  // =========================================================

  {
    q: "Nesne yönelimli programlamada nesne üretmek için kullanılan şablon yapı hangisidir?",
    t: "mcq",
    o: ["Object", "Class", "Method", "Property", "Constructor"],
    a: 1,
    difficulty: "easy",
    week: 1,
    topic: "Class",
    importance: 5,
    explanation: "Soruda şablon, taslak veya nesne üretir ifadesi varsa cevap Class/Sınıf olur."
  },
  {
    q: "Bir sınıftan üretilen gerçek örneğe ne denir?",
    t: "mcq",
    o: ["Method", "Property", "Object", "Interface", "Namespace"],
    a: 2,
    difficulty: "easy",
    week: 1,
    topic: "Object",
    importance: 5,
    explanation: "Class şablondur, Object ise o şablondan üretilen gerçek örnektir."
  },
  {
    q: "Bir sınıfın ad, yaş, renk, marka gibi bilgilerine ne denir?",
    t: "mcq",
    o: ["Method", "Loop", "Property / Özellik", "Constructor", "Exception"],
    a: 2,
    difficulty: "easy",
    week: 1,
    topic: "Property",
    importance: 5,
    explanation: "Soruda bir nesnenin bilgileri, durumu veya özellikleri geçiyorsa cevap Property/Özellik olur."
  },
  {
    q: "Bir sınıfın çalıştır, hesapla, yazdır gibi davranışlarını temsil eden yapı hangisidir?",
    t: "mcq",
    o: ["Class", "Method", "Field", "Object", "Namespace"],
    a: 1,
    difficulty: "easy",
    week: 1,
    topic: "Method",
    importance: 5,
    explanation: "Soruda davranış, işlem veya eylem geçiyorsa cevap Method/Metot olur."
  },
  {
    q: "Nesne oluşturulurken çalışan ve ilk değerleri atamak için kullanılan özel metot hangisidir?",
    t: "mcq",
    o: ["Destructor", "Loop", "Constructor", "Interface", "Property"],
    a: 2,
    difficulty: "medium",
    week: 2,
    topic: "Constructor",
    importance: 5,
    explanation: "Soruda nesne oluşurken çalışır veya ilk değer atar deniyorsa cevap Constructor/Yapıcı metot olur."
  },
  {
    q: "OOP'nin dört temel ilkesi hangileridir?",
    t: "mcq",
    o: [
      "SELECT, INSERT, UPDATE, DELETE",
      "if, else, for, while",
      "HTML, CSS, JavaScript, SQL",
      "Encapsulation, Inheritance, Polymorphism, Abstraction",
      "public, private, static, void"
    ],
    a: 3,
    difficulty: "easy",
    week: 1,
    topic: "OOP İlkeleri",
    importance: 5,
    explanation: "OOP'nin temel dört ilkesi kapsülleme, kalıtım, çok biçimlilik ve soyutlamadır."
  },
  {
    q: "Veriyi dışarıdan doğrudan erişime kapatıp kontrollü erişim sağlamaya ne denir?",
    t: "mcq",
    o: ["Inheritance", "Encapsulation", "Polymorphism", "Abstraction", "Overloading"],
    a: 1,
    difficulty: "medium",
    week: 2,
    topic: "Encapsulation",
    importance: 5,
    explanation: "Soruda private alan, getter/setter veya veriyi koruma geçiyorsa cevap Encapsulation/Kapsülleme olur."
  },
  {
    q: "Bir sınıfın başka bir sınıftan özellik ve metot almasına ne denir?",
    t: "mcq",
    o: ["Encapsulation", "Polymorphism", "Inheritance", "Abstraction", "Composition"],
    a: 2,
    difficulty: "easy",
    week: 3,
    topic: "Inheritance",
    importance: 5,
    explanation: "Soruda miras alma, üst sınıf-alt sınıf veya base-derived geçiyorsa cevap Inheritance/Kalıtım olur."
  },
  {
    q: "Aynı metodun farklı sınıflarda farklı davranabilmesi hangi OOP ilkesidir?",
    t: "mcq",
    o: ["Abstraction", "Encapsulation", "Inheritance", "Polymorphism", "Constructor"],
    a: 3,
    difficulty: "medium",
    week: 4,
    topic: "Polymorphism",
    importance: 5,
    explanation: "Soruda aynı isim farklı davranış veya aynı çağrı farklı sonuç geçiyorsa cevap Polymorphism/Çok biçimlilik olur."
  },
  {
    q: "Gereksiz detayları gizleyip sadece gerekli kısmı göstermeye ne denir?",
    t: "mcq",
    o: ["Abstraction", "Inheritance", "Encapsulation", "Overloading", "Composition"],
    a: 0,
    difficulty: "medium",
    week: 4,
    topic: "Abstraction",
    importance: 5,
    explanation: "Soruda detay gizleme veya sadece gerekli bilgiyi gösterme geçiyorsa cevap Abstraction/Soyutlama olur."
  },
  {
    q: "Sadece sınıf içinden erişilebilen erişim belirleyici hangisidir?",
    t: "mcq",
    o: ["public", "private", "protected", "static", "virtual"],
    a: 1,
    difficulty: "easy",
    week: 2,
    topic: "private",
    importance: 5,
    explanation: "Soruda yalnızca kendi sınıfı içinde erişim deniyorsa cevap private olur."
  },
  {
    q: "Her yerden erişilebilen erişim belirleyici hangisidir?",
    t: "mcq",
    o: ["protected", "private", "public", "abstract", "override"],
    a: 2,
    difficulty: "easy",
    week: 2,
    topic: "public",
    importance: 5,
    explanation: "Soruda her yerden erişim deniyorsa cevap public olur."
  },
  {
    q: "Kendi sınıfı ve ondan türeyen sınıflardan erişilebilen erişim belirleyici hangisidir?",
    t: "mcq",
    o: ["public", "private", "static", "protected", "sealed"],
    a: 3,
    difficulty: "medium",
    week: 2,
    topic: "protected",
    importance: 4,
    explanation: "Soruda miras alan sınıf da erişebilir deniyorsa cevap protected olur."
  },
  {
    q: "Nesne oluşturmadan sınıf adıyla kullanılabilen elemanlar için hangi anahtar kelime kullanılır?",
    t: "mcq",
    o: ["static", "private", "virtual", "override", "new"],
    a: 0,
    difficulty: "medium",
    week: 3,
    topic: "static",
    importance: 5,
    explanation: "Soruda nesne oluşturmadan çağrılır veya sınıfa aittir deniyorsa cevap static olur."
  },
  {
    q: "Aynı isimli metodun farklı parametrelerle yazılmasına ne denir?",
    t: "mcq",
    o: ["Overriding", "Overloading", "Inheritance", "Abstraction", "Interface"],
    a: 1,
    difficulty: "medium",
    week: 5,
    topic: "Method Overloading",
    importance: 5,
    explanation: "Soruda aynı metot adı ve farklı parametre geçiyorsa cevap Method Overloading olur."
  },
  {
    q: "Üst sınıftaki metodun alt sınıfta yeniden yazılmasına ne denir?",
    t: "mcq",
    o: ["Encapsulation", "Overloading", "Overriding", "Composition", "Constructor"],
    a: 2,
    difficulty: "medium",
    week: 5,
    topic: "Method Overriding",
    importance: 5,
    explanation: "Soruda miras alınan metodu yeniden tanımlama geçiyorsa cevap Method Overriding olur."
  },
  {
    q: "C#'ta mevcut nesneyi ifade eden anahtar kelime hangisidir?",
    t: "mcq",
    o: ["base", "new", "static", "this", "void"],
    a: 3,
    difficulty: "medium",
    week: 4,
    topic: "this",
    importance: 4,
    explanation: "Soruda bu nesne veya mevcut sınıf örneği geçiyorsa cevap this olur."
  },
  {
    q: "C#'ta üst sınıfın constructor veya metoduna erişmek için kullanılan anahtar kelime hangisidir?",
    t: "mcq",
    o: ["base", "this", "new", "public", "return"],
    a: 0,
    difficulty: "medium",
    week: 4,
    topic: "base",
    importance: 4,
    explanation: "Soruda üst sınıfı çağırma veya base class erişimi geçiyorsa cevap base olur."
  },
  {
    q: "Nesne oluşturmak için kullanılan anahtar kelime hangisidir?",
    t: "mcq",
    o: ["void", "new", "return", "static", "get"],
    a: 1,
    difficulty: "easy",
    week: 1,
    topic: "new",
    importance: 5,
    explanation: "Soruda nesne oluşturma geçiyorsa cevap new olur."
  },
  {
    q: "Sınıflara uygulanması gereken davranışları sözleşme gibi belirleyen yapı hangisidir?",
    t: "mcq",
    o: ["Class", "Object", "Interface", "Property", "Field"],
    a: 2,
    difficulty: "medium",
    week: 6,
    topic: "Interface",
    importance: 5,
    explanation: "Soruda sözleşme, uygulamak zorunda veya implements geçiyorsa cevap Interface olur."
  },
  {
    q: "Nesne üretilemeyen, ortak özellik ve davranışları taşıyan sınıf türü hangisidir?",
    t: "mcq",
    o: ["static method", "interface only", "sealed class", "abstract class", "object"],
    a: 3,
    difficulty: "medium",
    week: 6,
    topic: "Abstract Class",
    importance: 5,
    explanation: "Soruda nesne oluşturulamaz veya soyut sınıf geçiyorsa cevap abstract class olur."
  },
  {
    q: "Bir sınıftan başka sınıf türetmek hangi OOP ilkesiyle ilgilidir?",
    t: "mcq",
    o: ["Inheritance", "Encapsulation", "Polymorphism", "Abstraction", "Exception"],
    a: 0,
    difficulty: "easy",
    week: 3,
    topic: "Inheritance",
    importance: 5,
    explanation: "Soruda sınıftan sınıf türetme veya üst-alt sınıf geçiyorsa cevap kalıtımdır."
  },
  {
    q: "Bir sınıfın başka bir sınıfı içinde nesne olarak kullanmasına ne denir?",
    t: "mcq",
    o: ["Inheritance", "Composition", "Polymorphism", "Override", "Static"],
    a: 1,
    difficulty: "medium",
    week: 6,
    topic: "Composition",
    importance: 4,
    explanation: "Soruda has-a ilişkisi veya Arabanın Motoru vardır gibi ifade geçiyorsa cevap Composition olur."
  },
  {
    q: "Kalıtım hangi ilişkiyi temsil eder?",
    t: "mcq",
    o: ["has-a", "part-of", "is-a", "uses-a", "calls-a"],
    a: 2,
    difficulty: "medium",
    week: 3,
    topic: "is-a",
    importance: 4,
    explanation: "Kedi bir hayvandır gibi ifadeler is-a ilişkisidir ve kalıtımla ilgilidir."
  },
  {
    q: "Composition hangi ilişkiyi temsil eder?",
    t: "mcq",
    o: ["is-a", "inherits-a", "extends-a", "has-a", "overrides-a"],
    a: 3,
    difficulty: "medium",
    week: 6,
    topic: "has-a",
    importance: 4,
    explanation: "Arabanın motoru vardır gibi ifadeler has-a ilişkisidir ve composition ile ilgilidir."
  },
  {
    q: "Bir sınıfın içindeki verileri güvenli hale getirmek için en çok kullanılan OOP ilkesi hangisidir?",
    t: "mcq",
    o: ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction", "Overloading"],
    a: 0,
    difficulty: "medium",
    week: 2,
    topic: "Encapsulation",
    importance: 5,
    explanation: "Soruda veri güvenliği, private alan veya getter/setter geçiyorsa Encapsulation düşünülür."
  },
  {
    q: "Kod tekrarını azaltmak ve ortak özellikleri üst sınıfta toplamak için hangi OOP ilkesi kullanılır?",
    t: "mcq",
    o: ["Encapsulation", "Inheritance", "Abstraction", "Interface", "Constructor"],
    a: 1,
    difficulty: "medium",
    week: 3,
    topic: "Inheritance",
    importance: 5,
    explanation: "Ortak özellikleri üst sınıfa koyup alt sınıflarda kullanmak kalıtımın temel amacıdır."
  },
  {
    q: "Aynı komutla farklı nesnelerin farklı davranabilmesi hangi OOP ilkesidir?",
    t: "mcq",
    o: ["Inheritance", "Encapsulation", "Polymorphism", "Static", "Private"],
    a: 2,
    difficulty: "medium",
    week: 4,
    topic: "Polymorphism",
    importance: 5,
    explanation: "Soruda aynı çağrı farklı sonuç veya farklı nesneler farklı davranır geçiyorsa cevap Polymorphism olur."
  },
  {
    q: "Bir sınıfın hangi verileri tutacağını, nesnenin ise bu sınıftan oluşturulan gerçek örnek olduğunu anlatan fark hangisidir?",
    t: "mcq",
    o: [
      "Method işlem, property döngüdür",
      "Class nesnedir, object şablondur",
      "Class şablondur, object gerçek örnektir",
      "Interface nesne üretir, class üretmez",
      "Constructor sadece hata yakalar"
    ],
    a: 2,
    difficulty: "easy",
    week: 1,
    topic: "Class Object Farkı",
    importance: 5,
    explanation: "Class şablon, object ise o şablondan üretilen gerçek örnektir."
  },

  // =========================================================
  // ===================== VERİ YAPILARI =====================
  // =========================================================

  {
    q: "Elemanlara indeks numarasıyla hızlı erişim sağlayan veri yapısı hangisidir?",
    t: "mcq",
    o: ["Dizi", "Stack", "Queue", "Graf", "AVL"],
    a: 0,
    difficulty: "easy",
    week: 2,
    topic: "Dizi",
    importance: 5,
    explanation: "Soruda indeksle hızlı erişim veya yan yana saklama geçiyorsa cevap Dizi olur."
  },
  {
    q: "Her elemanın veri ve sonraki elemanın adresini tuttuğu veri yapısı hangisidir?",
    t: "mcq",
    o: ["Dizi", "Bağlı liste", "Heap", "Quick Sort", "BFS"],
    a: 1,
    difficulty: "easy",
    week: 3,
    topic: "Bağlı Liste",
    importance: 5,
    explanation: "Soruda düğüm, sonraki adres veya dinamik yapı geçiyorsa cevap Bağlı liste olur."
  },
  {
    q: "Son giren ilk çıkar mantığıyla çalışan veri yapısı hangisidir?",
    t: "mcq",
    o: ["Queue", "Graf", "Stack", "Dizi", "Merge Sort"],
    a: 2,
    difficulty: "easy",
    week: 4,
    topic: "Stack",
    importance: 5,
    explanation: "Soruda LIFO veya son giren ilk çıkar geçiyorsa cevap Stack olur."
  },
  {
    q: "İlk giren ilk çıkar mantığıyla çalışan veri yapısı hangisidir?",
    t: "mcq",
    o: ["Stack", "BST", "Dizi", "Queue", "Bubble Sort"],
    a: 3,
    difficulty: "easy",
    week: 5,
    topic: "Queue",
    importance: 5,
    explanation: "Soruda FIFO veya ilk giren ilk çıkar geçiyorsa cevap Queue olur."
  },
  {
    q: "Stack veri yapısına eleman ekleme işlemi hangisidir?",
    t: "mcq",
    o: ["Push", "Pop", "Dequeue", "Enqueue", "Search"],
    a: 0,
    difficulty: "easy",
    week: 4,
    topic: "Stack İşlemleri",
    importance: 5,
    explanation: "Stack + ekleme sorulursa cevap Push olur. Stack + çıkarma sorulursa Pop olur."
  },
  {
    q: "Stack veri yapısından eleman çıkarma işlemi hangisidir?",
    t: "mcq",
    o: ["Enqueue", "Pop", "Rear", "Insert", "Binary Search"],
    a: 1,
    difficulty: "easy",
    week: 4,
    topic: "Stack İşlemleri",
    importance: 5,
    explanation: "Stack'ten çıkarma Pop'tur. Queue'dan çıkarma ise Dequeue'dur."
  },
  {
    q: "Queue veri yapısına eleman ekleme işlemi hangisidir?",
    t: "mcq",
    o: ["Push", "Pop", "Enqueue", "Peek", "Pivot"],
    a: 2,
    difficulty: "easy",
    week: 5,
    topic: "Queue İşlemleri",
    importance: 5,
    explanation: "Queue + ekleme sorulursa cevap Enqueue olur."
  },
  {
    q: "Queue veri yapısından eleman çıkarma işlemi hangisidir?",
    t: "mcq",
    o: ["Push", "Pop", "Peek", "Dequeue", "Rotate"],
    a: 3,
    difficulty: "easy",
    week: 5,
    topic: "Queue İşlemleri",
    importance: 5,
    explanation: "Queue'dan çıkarma Dequeue'dur. Stack'ten çıkarma Pop'tur."
  },
  {
    q: "Her düğümün en fazla iki çocuğu olan ağaç türü hangisidir?",
    t: "mcq",
    o: ["Binary Tree", "Graf", "Queue", "Bubble Sort", "Hash tablo"],
    a: 0,
    difficulty: "easy",
    week: 7,
    topic: "Binary Tree",
    importance: 5,
    explanation: "Soruda en fazla iki çocuk, sol çocuk veya sağ çocuk geçiyorsa cevap Binary Tree olur."
  },
  {
    q: "BST'de küçük değerler nereye yerleştirilir?",
    t: "mcq",
    o: ["Sağ alt ağaca", "Sol alt ağaca", "Kökün üstüne", "Queue'nun sonuna", "Stack'e"],
    a: 1,
    difficulty: "easy",
    week: 8,
    topic: "BST",
    importance: 5,
    explanation: "BST kuralı: küçük değerler sola, büyük değerler sağa gider."
  },
  {
    q: "BST'de büyük değerler nereye yerleştirilir?",
    t: "mcq",
    o: ["Kökün üstüne", "Sol alt ağaca", "Sağ alt ağaca", "Queue'nun başına", "Stack'in altına"],
    a: 2,
    difficulty: "easy",
    week: 8,
    topic: "BST",
    importance: 5,
    explanation: "BST kuralı: küçük sol, büyük sağ."
  },
  {
    q: "BST'de değerleri küçükten büyüğe veren dolaşma yöntemi hangisidir?",
    t: "mcq",
    o: ["Preorder", "Postorder", "Levelorder", "Inorder", "DFS only"],
    a: 3,
    difficulty: "medium",
    week: 8,
    topic: "Inorder",
    importance: 5,
    explanation: "BST + küçükten büyüğe sıralı sonuç deniyorsa cevap Inorder olur."
  },
  {
    q: "Inorder dolaşma sırası hangisidir?",
    t: "mcq",
    o: ["Sol - Kök - Sağ", "Kök - Sol - Sağ", "Sol - Sağ - Kök", "Kök - Sağ - Sol", "Sağ - Kök - Sol"],
    a: 0,
    difficulty: "medium",
    week: 8,
    topic: "Traversal",
    importance: 5,
    explanation: "Inorder sırası Sol - Kök - Sağ şeklindedir."
  },
  {
    q: "Preorder dolaşma sırası hangisidir?",
    t: "mcq",
    o: ["Sol - Kök - Sağ", "Kök - Sol - Sağ", "Sol - Sağ - Kök", "Sağ - Sol - Kök", "Kök - Sağ - Sol - Kök"],
    a: 1,
    difficulty: "medium",
    week: 8,
    topic: "Traversal",
    importance: 4,
    explanation: "Preorder'da kök önce gelir. Sıra Kök - Sol - Sağ şeklindedir."
  },
  {
    q: "Postorder dolaşma sırası hangisidir?",
    t: "mcq",
    o: ["Kök - Sol - Sağ", "Sol - Kök - Sağ", "Sol - Sağ - Kök", "Kök - Sağ - Sol", "Sağ - Kök - Sol"],
    a: 2,
    difficulty: "medium",
    week: 8,
    topic: "Traversal",
    importance: 4,
    explanation: "Postorder'da kök en son gelir. Sıra Sol - Sağ - Kök şeklindedir."
  },
  {
    q: "Kendini dengede tutan ikili arama ağacı hangisidir?",
    t: "mcq",
    o: ["Heap", "B ağacı", "Graf", "AVL", "Queue"],
    a: 3,
    difficulty: "medium",
    week: 9,
    topic: "AVL",
    importance: 5,
    explanation: "Soruda dengeli BST, denge faktörü veya rotasyon geçiyorsa cevap AVL olur."
  },
  {
    q: "AVL ağacında denge bozulursa hangi işlem yapılır?",
    t: "mcq",
    o: ["Rotasyon", "Dequeue", "Push", "Binary Search", "Bubble Sort"],
    a: 0,
    difficulty: "medium",
    week: 9,
    topic: "AVL Rotasyon",
    importance: 5,
    explanation: "AVL'de denge bozulursa ağacı düzeltmek için rotasyon yapılır."
  },
  {
    q: "Max Heap yapısında kökte hangi eleman bulunur?",
    t: "mcq",
    o: ["En küçük eleman", "En büyük eleman", "Son eklenen eleman", "İlk eklenen eleman", "Rastgele eleman"],
    a: 1,
    difficulty: "medium",
    week: 7,
    topic: "Heap",
    importance: 4,
    explanation: "Max maksimum demektir. Max Heap'te kökte en büyük eleman bulunur."
  },
  {
    q: "Min Heap yapısında kökte hangi eleman bulunur?",
    t: "mcq",
    o: ["En büyük eleman", "Rastgele eleman", "En küçük eleman", "Son eklenen eleman", "İlk silinen eleman"],
    a: 2,
    difficulty: "medium",
    week: 7,
    topic: "Heap",
    importance: 4,
    explanation: "Min minimum demektir. Min Heap'te kökte en küçük eleman bulunur."
  },
  {
    q: "Büyük veri ve veritabanı indekslerinde kullanılan dengeli çok dallı ağaç hangisidir?",
    t: "mcq",
    o: ["AVL", "Binary Tree", "Heap", "B Ağacı", "Stack"],
    a: 3,
    difficulty: "medium",
    week: 9,
    topic: "B Ağacı",
    importance: 4,
    explanation: "Soruda veritabanı, disk, büyük veri veya çok dallı ağaç geçiyorsa cevap B Ağacı olur."
  },
  {
    q: "Verileri baştan sona tek tek kontrol eden arama algoritması hangisidir?",
    t: "mcq",
    o: ["Linear Search", "Binary Search", "Quick Sort", "Merge Sort", "DFS"],
    a: 0,
    difficulty: "easy",
    week: 12,
    topic: "Linear Search",
    importance: 5,
    explanation: "Soruda tek tek arama veya sıralama gerekmez geçiyorsa cevap Linear Search olur."
  },
  {
    q: "Sıralı veride ortadan başlayarak arama yapan algoritma hangisidir?",
    t: "mcq",
    o: ["Linear Search", "Binary Search", "Bubble Sort", "Selection Sort", "BFS"],
    a: 1,
    difficulty: "easy",
    week: 12,
    topic: "Binary Search",
    importance: 5,
    explanation: "Soruda sıralı veri, ortadan arama veya yarıya bölme geçiyorsa cevap Binary Search olur."
  },
  {
    q: "Binary Search algoritmasının doğru çalışması için en önemli şart hangisidir?",
    t: "mcq",
    o: ["Verinin rastgele olması", "Verinin stack içinde olması", "Verinin sıralı olması", "Verinin graf olması", "Verinin ağaç olması"],
    a: 2,
    difficulty: "medium",
    week: 12,
    topic: "Binary Search",
    importance: 5,
    explanation: "Binary Search sıralı veri ister. Veri sıralı değilse sağa mı sola mı gidileceği bilinemez."
  },
  {
    q: "Yan yana elemanları karşılaştırıp büyük olanı sona taşıyan sıralama algoritması hangisidir?",
    t: "mcq",
    o: ["Selection Sort", "Insertion Sort", "Merge Sort", "Bubble Sort", "Quick Sort"],
    a: 3,
    difficulty: "easy",
    week: 10,
    topic: "Bubble Sort",
    importance: 5,
    explanation: "Soruda yan yana karşılaştırma veya büyük eleman sona gider geçiyorsa cevap Bubble Sort olur."
  },
  {
    q: "Her turda en küçük elemanı seçip başa koyan sıralama algoritması hangisidir?",
    t: "mcq",
    o: ["Selection Sort", "Bubble Sort", "Insertion Sort", "Merge Sort", "Quick Sort"],
    a: 0,
    difficulty: "easy",
    week: 11,
    topic: "Selection Sort",
    importance: 5,
    explanation: "Soruda en küçüğü seç veya başa koy geçiyorsa cevap Selection Sort olur."
  },
  {
    q: "Kart dizer gibi elemanı doğru yerine yerleştiren sıralama algoritması hangisidir?",
    t: "mcq",
    o: ["Bubble Sort", "Insertion Sort", "Selection Sort", "Quick Sort", "Heap Sort"],
    a: 1,
    difficulty: "easy",
    week: 13,
    topic: "Insertion Sort",
    importance: 5,
    explanation: "Soruda kart dizer gibi, araya yerleştir veya doğru konuma ekle geçiyorsa cevap Insertion Sort olur."
  },
  {
    q: "Pivot kullanan sıralama algoritması hangisidir?",
    t: "mcq",
    o: ["Merge Sort", "Bubble Sort", "Quick Sort", "Selection Sort", "Linear Search"],
    a: 2,
    difficulty: "medium",
    week: 13,
    topic: "Quick Sort",
    importance: 4,
    explanation: "Soruda pivot kelimesi varsa cevap Quick Sort olur."
  },
  {
    q: "Böl ve birleştir mantığıyla çalışan sıralama algoritması hangisidir?",
    t: "mcq",
    o: ["Bubble Sort", "Selection Sort", "Insertion Sort", "Merge Sort", "Linear Search"],
    a: 3,
    difficulty: "medium",
    week: 13,
    topic: "Merge Sort",
    importance: 4,
    explanation: "Soruda böl ve birleştir veya divide and conquer geçiyorsa cevap Merge Sort olur."
  },
  {
    q: "Düğüm ve kenarlardan oluşan veri yapısı hangisidir?",
    t: "mcq",
    o: ["Graf", "Stack", "Queue", "Dizi", "Bubble Sort"],
    a: 0,
    difficulty: "easy",
    week: 14,
    topic: "Graf",
    importance: 5,
    explanation: "Soruda düğüm, kenar veya bağlantı geçiyorsa cevap Graf olur."
  },
  {
    q: "BFS ve DFS için doğru eşleştirme hangisidir?",
    t: "mcq",
    o: [
      "BFS Stack, DFS Queue kullanır",
      "BFS Queue, DFS Stack kullanır",
      "BFS Dizi, DFS Bağlı liste kullanır",
      "BFS Quick Sort, DFS Merge Sort kullanır",
      "BFS AVL, DFS Heap kullanır"
    ],
    a: 1,
    difficulty: "medium",
    week: 14,
    topic: "BFS DFS",
    importance: 5,
    explanation: "Bunu direkt ezberle: BFS = Queue, DFS = Stack."
  },

  // =========================================================
  // ============= KODLAMA / PROGRAMLAMA TEMELLERİ ===========
  // =========================================================

  {
    q: "Tam sayı tutmak için kullanılan veri tipi hangisidir?",
    t: "mcq",
    o: ["int", "string", "bool", "double", "char"],
    a: 0,
    difficulty: "easy",
    week: 1,
    topic: "Veri Tipleri",
    importance: 5,
    explanation: "Soruda tam sayı, 1, 5, 100 gibi değerler varsa cevap int olur."
  },
  {
    q: "Metin veya yazı tutmak için kullanılan veri tipi hangisidir?",
    t: "mcq",
    o: ["int", "string", "double", "bool", "float"],
    a: 1,
    difficulty: "easy",
    week: 1,
    topic: "Veri Tipleri",
    importance: 5,
    explanation: "Soruda ad, soyad, metin veya yazı geçiyorsa cevap string olur."
  },
  {
    q: "Doğru veya yanlış değer tutan veri tipi hangisidir?",
    t: "mcq",
    o: ["int", "double", "bool", "string", "decimal"],
    a: 2,
    difficulty: "easy",
    week: 1,
    topic: "Veri Tipleri",
    importance: 5,
    explanation: "Soruda true/false veya doğru/yanlış geçiyorsa cevap bool/boolean olur."
  },
  {
    q: "Ondalıklı sayı tutmak için kullanılan veri tipi hangisidir?",
    t: "mcq",
    o: ["string", "bool", "char", "double", "void"],
    a: 3,
    difficulty: "easy",
    week: 1,
    topic: "Veri Tipleri",
    importance: 5,
    explanation: "Soruda 3.14, 2.5 veya ondalıklı sayı geçiyorsa double/float düşünülür."
  },
  {
    q: "Bir koşula göre işlem yaptırmak için kullanılan yapı hangisidir?",
    t: "mcq",
    o: ["if-else", "for", "while", "class", "return"],
    a: 0,
    difficulty: "easy",
    week: 2,
    topic: "Koşul Yapıları",
    importance: 5,
    explanation: "Soruda eğer, şart veya koşul geçiyorsa cevap if-else olur."
  },
  {
    q: "Aynı değişkenin farklı sabit değerlerine göre seçim yapmak için kullanılan yapı hangisidir?",
    t: "mcq",
    o: ["if only", "switch-case", "while", "for", "try-catch"],
    a: 1,
    difficulty: "medium",
    week: 2,
    topic: "switch-case",
    importance: 5,
    explanation: "Soruda menü seçimi veya farklı sabit değerler geçiyorsa switch-case uygun olur."
  },
  {
    q: "Kaç kez çalışacağı belli olan tekrar işlemlerinde en çok kullanılan döngü hangisidir?",
    t: "mcq",
    o: ["while", "if", "for", "switch", "try"],
    a: 2,
    difficulty: "easy",
    week: 3,
    topic: "for Döngüsü",
    importance: 5,
    explanation: "Soruda belirli sayıda tekrar veya kaç kez döneceği belli deniyorsa cevap for olur."
  },
  {
    q: "Koşul doğru olduğu sürece çalışan döngü hangisidir?",
    t: "mcq",
    o: ["for", "switch", "if", "while", "return"],
    a: 3,
    difficulty: "easy",
    week: 3,
    topic: "while Döngüsü",
    importance: 5,
    explanation: "Soruda koşul sağlandıkça devam et deniyorsa cevap while olur."
  },
  {
    q: "En az bir kez çalışan döngü hangisidir?",
    t: "mcq",
    o: ["do-while", "for", "while", "foreach", "switch"],
    a: 0,
    difficulty: "medium",
    week: 3,
    topic: "do-while",
    importance: 4,
    explanation: "do-while önce çalışır, sonra koşulu kontrol eder. Bu yüzden en az bir kez çalışır."
  },
  {
    q: "Birden fazla değeri aynı isim altında saklayan yapı hangisidir?",
    t: "mcq",
    o: ["Metot", "Dizi", "Koşul", "Operatör", "Exception"],
    a: 1,
    difficulty: "easy",
    week: 4,
    topic: "Diziler",
    importance: 5,
    explanation: "Soruda birden fazla değer, aynı tür veya indeks geçiyorsa cevap Dizi olur."
  },
  {
    q: "Dizideki eleman sayısını veren özellik hangisidir?",
    t: "mcq",
    o: ["CountOnly", "SizeText", "Length", "IndexOf", "Return"],
    a: 2,
    difficulty: "medium",
    week: 4,
    topic: "Length",
    importance: 5,
    explanation: "Soruda dizinin uzunluğu veya eleman sayısı geçiyorsa cevap Length olur."
  },
  {
    q: "Bir sayının çift olup olmadığını kontrol etmek için en uygun ifade hangisidir?",
    t: "mcq",
    o: ["sayi + 2 == 0", "sayi / 2 == 0", "sayi * 2 == 0", "sayi % 2 == 0", "sayi == true"],
    a: 3,
    difficulty: "easy",
    week: 4,
    topic: "Tek Çift Kontrolü",
    importance: 5,
    explanation: "% kalan operatörüdür. Bir sayı 2'ye bölününce kalan 0 ise sayı çifttir."
  },
  {
    q: "% operatörü ne işe yarar?",
    t: "mcq",
    o: ["Bölmeden kalanı verir", "Toplama yapar", "Metin birleştirir", "Koşul başlatır", "Metot döndürür"],
    a: 0,
    difficulty: "easy",
    week: 4,
    topic: "Mod Operatörü",
    importance: 5,
    explanation: "% operatörü bölme işleminden kalanı verir. Tek/çift ve bölünebilme sorularında kullanılır."
  },
  {
    q: "Eşitlik karşılaştırması yapmak için kullanılan operatör hangisidir?",
    t: "mcq",
    o: ["=", "==", "+=", "!=", "&&"],
    a: 1,
    difficulty: "easy",
    week: 2,
    topic: "Karşılaştırma Operatörleri",
    importance: 5,
    explanation: "Tek = atama yapar. Çift == eşitlik kontrolü yapar."
  },
  {
    q: "Bir değişkene değer atamak için kullanılan operatör hangisidir?",
    t: "mcq",
    o: ["==", "!=", "=", "&&", "||"],
    a: 2,
    difficulty: "easy",
    week: 2,
    topic: "Atama Operatörü",
    importance: 5,
    explanation: "sayi = 5 ifadesi, sayi değişkenine 5 değerini atar."
  },
  {
    q: "İki şartın da doğru olması gerektiğinde kullanılan mantıksal operatör hangisidir?",
    t: "mcq",
    o: ["||", "==", "!=", "&&", "%"],
    a: 3,
    difficulty: "medium",
    week: 2,
    topic: "Mantıksal Operatörler",
    importance: 4,
    explanation: "&& operatörü ve anlamına gelir. İki koşulun da doğru olması gerekir."
  },
  {
    q: "Şartlardan en az birinin doğru olması yeterliyse kullanılan mantıksal operatör hangisidir?",
    t: "mcq",
    o: ["||", "&&", "==", "%", "="],
    a: 0,
    difficulty: "medium",
    week: 2,
    topic: "Mantıksal Operatörler",
    importance: 4,
    explanation: "|| operatörü veya anlamına gelir. Koşullardan biri doğruysa sonuç doğru olur."
  },
  {
    q: "Geriye değer döndürmeyen metot hangi anahtar kelimeyle tanımlanır?",
    t: "mcq",
    o: ["int", "void", "string", "bool", "return"],
    a: 1,
    difficulty: "easy",
    week: 8,
    topic: "Metotlar",
    importance: 5,
    explanation: "Soruda geriye değer döndürmez deniyorsa cevap void olur."
  },
  {
    q: "Geriye tam sayı döndüren metot hangi dönüş tipiyle tanımlanır?",
    t: "mcq",
    o: ["void", "string", "int", "bool", "object"],
    a: 2,
    difficulty: "medium",
    week: 8,
    topic: "Metotlar",
    importance: 5,
    explanation: "Metot geriye tam sayı döndürecekse dönüş tipi int olmalıdır."
  },
  {
    q: "Metoda dışarıdan gönderilen değere ne denir?",
    t: "mcq",
    o: ["Döngü", "Operatör", "Sabit", "Parametre", "Exception"],
    a: 3,
    difficulty: "medium",
    week: 8,
    topic: "Parametre",
    importance: 5,
    explanation: "Soruda metoda verilen değer veya dışarıdan gelen bilgi geçiyorsa cevap parametre olur."
  },
  {
    q: "Metottan sonucu geri döndürmek için kullanılan komut hangisidir?",
    t: "mcq",
    o: ["return", "break", "continue", "switch", "catch"],
    a: 0,
    difficulty: "easy",
    week: 8,
    topic: "return",
    importance: 5,
    explanation: "return, metottan sonucu geri göndermek için kullanılır."
  },
  {
    q: "Hata yakalamak ve programın çökmesini engellemek için kullanılan yapı hangisidir?",
    t: "mcq",
    o: ["if-else", "try-catch", "switch", "for", "return"],
    a: 1,
    difficulty: "medium",
    week: 12,
    topic: "try-catch",
    importance: 5,
    explanation: "Soruda hata yakalama veya program çökmesin geçiyorsa cevap try-catch olur."
  },
  {
    q: "Genel hata sınıfı hangisidir?",
    t: "mcq",
    o: ["FormatException", "Timer", "Exception", "DialogResult", "Convert"],
    a: 2,
    difficulty: "medium",
    week: 12,
    topic: "Exception",
    importance: 5,
    explanation: "Exception genel hata sınıfıdır. Farklı hata türlerini genel olarak yakalamak için kullanılabilir."
  },
  {
    q: "Metin olarak gelen bir değeri tam sayıya çevirmek için hangi yapı kullanılır?",
    t: "mcq",
    o: ["ToString()", "Math.Sqrt()", "Length", "Convert.ToInt32()", "Math.Abs()"],
    a: 3,
    difficulty: "medium",
    week: 3,
    topic: "Veri Dönüştürme",
    importance: 5,
    explanation: "TextBox gibi alanlardan gelen değer metindir. Tam sayı gerekiyorsa Convert.ToInt32 kullanılır."
  },
  {
    q: "Metin olarak gelen ondalıklı bir değeri sayıya çevirmek için hangi yapı kullanılır?",
    t: "mcq",
    o: ["Convert.ToDouble()", "ToString()", "Length", "Clear()", "ShowDialog()"],
    a: 0,
    difficulty: "medium",
    week: 3,
    topic: "Veri Dönüştürme",
    importance: 5,
    explanation: "Ondalıklı sayı gerekiyorsa Convert.ToDouble kullanılır."
  },
  {
    q: "Bir değeri metne çevirmek için kullanılan metot hangisidir?",
    t: "mcq",
    o: ["ToInt32()", "ToString()", "Clear()", "Add()", "ShowDialog()"],
    a: 1,
    difficulty: "easy",
    week: 3,
    topic: "ToString",
    importance: 5,
    explanation: "Label veya Text alanına sayı yazdırırken değer genellikle ToString ile metne çevrilir."
  },
  {
    q: "Bir sayının karekökünü almak için kullanılan Math metodu hangisidir?",
    t: "mcq",
    o: ["Math.Pow()", "Math.Abs()", "Math.Sqrt()", "Math.Round()", "Math.Min()"],
    a: 2,
    difficulty: "easy",
    week: 2,
    topic: "Math.Sqrt",
    importance: 4,
    explanation: "Soruda karekök geçiyorsa cevap Math.Sqrt olur."
  },
  {
    q: "Bir sayının mutlak değerini almak için kullanılan Math metodu hangisidir?",
    t: "mcq",
    o: ["Math.Sqrt()", "Math.Pow()", "Math.Round()", "Math.Abs()", "Math.Max()"],
    a: 3,
    difficulty: "medium",
    week: 2,
    topic: "Math.Abs",
    importance: 4,
    explanation: "Soruda mutlak değer veya negatif sayıyı pozitife çevirme geçiyorsa cevap Math.Abs olur."
  },
  {
    q: "Üs alma işlemi için kullanılan Math metodu hangisidir?",
    t: "mcq",
    o: ["Math.Pow()", "Math.Abs()", "Math.Sqrt()", "Math.Round()", "Math.Min()"],
    a: 0,
    difficulty: "medium",
    week: 2,
    topic: "Math.Pow",
    importance: 4,
    explanation: "Soruda üs alma veya karesini alma geçiyorsa Math.Pow kullanılır."
  },
  {
    q: "Bir işlemi tekrar tekrar kullanmak için yazılan kod bloğuna ne denir?",
    t: "mcq",
    o: ["Değişken", "Metot / Fonksiyon", "Operatör", "Koşul", "Hata"],
    a: 1,
    difficulty: "easy",
    week: 8,
    topic: "Metot",
    importance: 5,
    explanation: "Soruda tekrar kullanılabilir kod bloğu veya belirli işi yapan parça geçiyorsa cevap metot/fonksiyon olur."
  }
];
